echo$nitesh


__scrt_initialize_thread_safe_statics_platform_specificN(#�__scrt_uninitialize_thread_safe_statics�VWdW:@PG�dllmain_crt_dispatchB�P�dllmain_crt_process_attachN�� �`dllmain_crt_process_attach'::`1'::fin$0B$�
�h�dllmain_crt_process_detachNx!�`dllmain_crt_process_detach'::`1'::fin$0N�	*!�`dllmain_crt_process_detach'::`1'::fin$163%��dllmain_dispatchFT6/>!�`dllmain_dispatch'::`1'::filt$02� �dllmain_raw$�W�W�W$XPX�X�X�XY6<k	e��__get_entropy,Y����	/�P,�HYFQX
FeW]V�OEO�N	JUU�X�Q�F%MY�UiRuM}HeIYSQK�WYN�X�E%E�GiQS-Y�J�TW�L�N�PEG�L�G�DQ�W�X�V�F�V�MqP�IT}V�K�OALITqE%P�T	N�R%X�S�J�W�U1H	R-VYJ�KIU�@@0@@�  �@@�A � � @  @@  �  � @� $0<HT`lx����������� ,8DP\ht�����������(4@LXdp|����������$0<HT`l__guard_flagsN�?initialize_environment@__scrt_narrow_environment_policy@@SAHXZ_fltusedz2?__scrt_initialize_type_info@@YAXXZ_��??$DispatchCheckVerify@XV<lambda_d25451c2afc9c48657f693d0d24ddca8>@@@@YAX$$QEAV<lambda_d25451c2afc9c48657f693d0d24ddca8>@@@Z*�	??_7FDefaultModuleImpl@@6B@bJ�?$TSS0@?1??GetFeatureName@IEngineCrypto@@SA?AVFName@@XZ@4HAd2__scrt_current_native_startup_statet*@__security_cookie_complement_b�??_C@_0IJ@BPGKKNGJ@?$CIInCount?5?$DO?$DN?50?$CJ?5?$CG?$CG?5?$CI?$CIsizeof?$CIInCo@a��??$DispatchCheckVerify@XV<lambda_f80e41b8eff063eebcb63bb8e439d124>@@@@YAX$$QEAV<lambda_f80e41b8eff063eebcb63bb8e439d124>@@@Z�_tls_used2__imp_?Malloc@FMemory@@SAPEAX_KI@Z4& CloseHandle@<_CRT_INIT&x__imp_GetCurrentThreadIdP&�_configure_narrow_argvP"� __vcrt_thread_attachvD ResetEvent_�??_V@YAXPEAX@Za&� _guard_dispatch_icall_nopr�
??_C@_1BCM@DJFBIBOM@?$AAA?$AAt?$AAt?$AAe?$AAm?$AAp?$AAt?$AAi?$AAn?$AAg?$AA?5?$AAt?$AAo?$AA?5?$AAu@e*�?GNameBlocksDebug@@3PEAPEAEEA"�_Init_thread_epochE"__guard_longjmp_count�__xp_ao*� _is_c_termination_complete@_RTC_Initialize_p__imp__crt_atexit"� __vcrt_thread_detachp*� SetUnhandledExceptionFilter�__imp_terminatet@??_U@YAPEAX_K@Ztp__rtc_taa�__imp__initterm_e"�ReadPointerNoFenceF>�api-ms-win-crt-runtime-l1-1-0_NULL_THUNK_DATAp&0__scrt_is_ucrt_dll_in_use6�	?GetEngineCrypto@@YAPEAUIEngineCrypto@@XZ� __vcrt_initialize __imp_SetEvent.h__imp__initialize_onexit_tableyr0
??_C@_1IO@PCOMPCDF@?$AAD?$AAa?$AAt?$AAa?$AA?5?$AAl?$AAo?$AAs?$AAt?$AA?5?$AAw?$AAh?$AAe?$AAn?$AA?5@e*�__guard_dispatch_icall_fptr?.P__imp_InitializeCriticalSectiont6�??_C@_19ONCOABMF@?$AA1?$AA1?$AA1?$AA0@A6�__imp_??0FName@@QEAA@PEB_WW4EFindName@@@Z`__rtc_iaa:�
?GetBlocks@FNameDebugVisualizer@@SAPEAPEAEXZ?"� __acrt_thread_attachV�_tls_endr�ReadNoFence64�__xc_ac"�__imp_GetStartupInfoW"x_pDefaultRawDllMain&P__scrt_ucrt_dll_is_in_use&� IsProcessorFeaturePresentR??$CheckVerifyFailed@$$BY0DH@_WHH@FDebug@@SAXPEBD0HAEAY0DH@$$CB_WHH@Z(__memcpy_nt_iters__guard_iat_table�@??$CheckVerifyFailed@$$BY0JG@_WPEBQEAUIEngineCrypto@@PEBQEAU1@HH_K@FDebug@@SAXPEBD0HAEAY0JG@$$CB_WPEBQEAUIEngineCrypto@@2HH_K@Z>�
?CheckVerifyFailedImpl@FDebug@@CAXPEBD0HPEB_WZZt6p
?StartupModule@IModuleInterface@@UEAAXXZE@__imp_memsete